### ISSUE TITLE
Add axis labels to 3D Scatter Plot

### ISSUE THREAD

**Issue by robintw** [glue-viz/glue-vispy-viewers#157]
I notice that that currently there are no axis labels on the 3D Scatter Plot, and I can't see any way to turn them on.

Is this natively supported by VisPy? Or would we have to implement it ourselves?

I found that after zooming and rotating a bit I kinda lost the context of where I was and which axis was which...

**Comment by astrofrog** [comment]
There is a PR to add tick labels (https://github.com/glue-viz/glue-vispy-viewers/pull/96) and I've opened a PR to VisPy to add axis labels to the class we use for the tick labels (https://github.com/vispy/vispy/pull/1199). It's not super pretty, but probably worth finishing up, otherwise it is indeed a little too easy to get lost!

**Comment by astrofrog** [comment]
@robintw - this should now be done!
