### ISSUE TITLE
Add side panel to control appearance of 3-d view

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#4]
This is done by adding an `options_widget` method on the data viewer class, as described here:

http://www.glueviz.org/en/stable/customizing_guide/full_custom_qt_viewer.html#adding-side-panels

This was done here in the VTK viewer:

https://github.com/astrofrog/cube-viewer/blob/master/cube_viewer/glue_viewer.py#L25

**Comment by PennyQ** [comment]
I would like to work on it. 
I will also try to add some instructions for key-press operations in the 3D viewer :)

**Comment by astrofrog** [comment]
Great! I've assigned you to this issue (see on the right). We can use this to keep track of who is working on what. Feel free to assign issues to yourself in this way.

**Comment by PennyQ** [comment]
Ok, then I will assign issues to myself directly.

**Comment by ChrisBeaumont** [comment]
While the keypresses are nice for the standalone viewer, I think we should think carefully about how best define what keypresses / mouse events do in the context of a Glue viewer. Where possible, we should follow glue's UI conventions (which is more mouse / menu driven then keyboard driven). So for example, toggling color maps should probably be done via a toolbar dropdown like the image viewer. 

> I will also try to add some instructions for key-press operations in the 3D viewer :)

I can think of 2 good ways to document any keyboard shortcuts. First, if these shortcuts also have some sort of widget on the control panel, then the visual status of that widget is a good reminder for the current state.

Second, the ginga project does a nice job about showing on-screen instructions for what the keyboard and mouse do, depending on the current interaction mode.

**Comment by PennyQ** [comment]
@astrofrog I followed the code written by you in `cube-viewer` and tried to get the directory of `options_widget.ui` in the `options_widget.py` through

```
UI_MAIN = os.path.join(os.path.dirname(__file__), 'options_widget.ui')
```

but then got an error as: 

`IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/glue/qt/ui/usr/local/lib/python2.7/site-packages/glue_3d_viewer-0.1.dev0-py2.7.egg/vispy_volume/options_widget.ui’`

I guess that this might be because `options_widget.py` is actually called in `/usr/local/lib/python2.7/site-packages/glue_3d_viewer-0.1.dev0-py2.7.egg`( which is installed by setup.py)  rather than in the directory that the code is located. Do you have any idea about this problem?

P.s. The glue_viewer code has been pushed to my remote repository 
https://github.com/PennyQ/glue-3d-viewer.git in `side_panel` branch

**Comment by astrofrog** [comment]
@PennyQ - yes, the issue is that the `setup.py` file should include a line like this:

https://github.com/astrofrog/cube-viewer/blob/master/setup.py#L16

to make sure the ui files get installed too. Can you try and see if you can get it to work once you add this to the `setup.py` file here? (note that you'll need to replace `cube_viewer` by `vispy_volume`)

**Comment by astrofrog** [comment]
Done :)
